### ISSUE TITLE
很赞、提几个个小建议

### ISSUE THREAD

**Issue by warmhug** [maotong06/vscode-editor-group-minimizer-plus#5]
![image](https://github.com/user-attachments/assets/9fd6c30d-7f4e-45f9-bb83-d363f00a6e45)

- 面板上 x 按钮应该放到最后，现在放第一个很容易误点击。
- 能增加 “保存到(和读取)本地文件” 的功能吗，把这些 文件路径 保存下来、能在多台电脑上共用。
- 文件路径比较长时，要滚动到最后边才能看到文件名。建议展示格式以文件名为主，比如：文件名 + 文件路径(灰色字)

**Comment by maotong06** [comment]
> ![image](https://private-user-images.githubusercontent.com/2011119/356082291-9fd6c30d-7f4e-45f9-bb83-d363f00a6e45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1OTgyMjcsIm5iZiI6MTcyNDU5NzkyNywicGF0aCI6Ii8yMDExMTE5LzM1NjA4MjI5MS05ZmQ2YzMwZC03ZjRlLTQ1ZjktYmI4My1kMzYzZjAwYTZlNDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjVUMTQ1ODQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmI5ODBlOTdlYjI3NTNmM2YxZDIwOTMwYjczMWYyYzY3MDQ2OGQ3MWUyOTllMDM1ZTU2NmVkNTE3YzM5NTk4MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lfk74cVQB2nr4IEB21O12Ma1XYu7COXCLtnQbZBES6Q)
> 
> * 面板上 x 按钮应该放到最后，现在放第一个很容易误点击。
> * 能增加 “保存到(和读取)本地文件” 的功能吗，把这些 文件路径 保存下来、能在多台电脑上共用。
> * 文件路径比较长时，要滚动到最后边才能看到文件名。建议展示格式以文件名为主，比如：文件名 + 文件路径(灰色字)

谢谢宝贵建议，已升级发布
